

services:
  evently.api:
    image: ${DOCKER_REGISTRY-}eventlyapi
    container_name: Evently.Api
    build:
      context: .
      dockerfile: src/API/Evently.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - evently.database

  evently.database:
    image: postgres:latest
    container_name: Evently.Database
    environment:
      - POSTGRES_DB=evently
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sqluser10$
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  evently.seq:
    image: datalust/seq:latest
    container_name: Evently.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8002:80"
  
  evently.redis:
    image: redis:latest
    container_name: Evently.Redis
    restart: always
    ports:
      - "6379:6379"
        
  
  evently.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: Evently.Identity
#    build:
#      context: .
#      dockerfile: src/Common/Evently.Common.Infrastructure/Dockerfile
    command: start-dev --import-realm
    environment:
      - KC_DB=postgres
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    env_file:
      - ./src/Common/Evently.Common.Infrastructure/env/keycloak.env
    volumes:
      - ./.files:/opt/keycloak/data/import
      - ./.containers/identity:/opt/keycloak/data
    ports:
      - "18080:8080"
    depends_on:
      - evently.database
    
